import { DatePipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { debounceTime, distinctUntilChanged, Observable } from 'rxjs';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { ApiService } from '../../core/api.service';
import { ManagedUserSummary, PagedResult, RoleSummary } from '../../core/models';

@Component({
  selector:'app-admin-page',
  imports:[DatePipe,ReactiveFormsModule,MatButtonModule,MatFormFieldModule,MatIconModule,MatInputModule,MatProgressSpinnerModule,MatSlideToggleModule],
  template:`
    <div class="page-heading"><div><span>ADMINISTRATION</span><h1>{{mode==='users'?'User management':'Role management'}}</h1><p>{{mode==='users'?'Review access, roles, and account status.':'Understand how responsibilities are divided across CloudTrack.'}}</p></div></div>
    @if(loading()){<div class="state"><mat-spinner diameter="34" /></div>}@else if(forbidden()){<div class="state denied"><mat-icon>lock</mat-icon><h2>Admin access required</h2><p>Your account is secure, but it does not have permission to view this workspace.</p></div>}@else if(error()){<div class="state"><mat-icon>cloud_off</mat-icon><h2>Couldn’t load administration data</h2><p>{{error()}}</p><button mat-stroked-button (click)="load()">Try again</button></div>}@else if(mode==='users'){
      <div class="toolbar"><mat-form-field appearance="outline" subscriptSizing="dynamic"><mat-icon matPrefix>search</mat-icon><input matInput [formControl]="search" placeholder="Search users" /></mat-form-field><span>{{users().length}} accounts</span></div>
      <section class="table"><header><span>User</span><span>Role</span><span>Last active</span><span>Status</span></header>@for(user of users();track user.id){<article><div class="identity"><i>{{initials(user.displayName)}}</i><p><strong>{{user.displayName}}</strong><small>{{user.email}}</small></p></div><div class="roles">@for(role of user.roles;track role){<b>{{role}}</b>}</div><span class="muted">{{user.lastLoginAt?(user.lastLoginAt|date:'MMM d, y'):'Never'}}</span><mat-slide-toggle [checked]="user.isActive" (change)="toggle(user,$event.checked)">{{user.isActive?'Active':'Inactive'}}</mat-slide-toggle></article>}</section>
    }@else{<section class="role-grid">@for(role of roles();track role.id){<article><div class="role-icon"><mat-icon>{{roleIcon(role.name)}}</mat-icon></div><h2>{{role.name}}</h2><p>{{role.description}}</p><footer><span><strong>{{role.userCount}}</strong> assigned users</span><span class="badge">System role</span></footer></article>}</section>}
  `,
  styles:`
    .page-heading span{color:#2563eb;font-size:11px;font-weight:800;letter-spacing:.15em}.page-heading h1{margin:7px 0 6px;color:#0f172a;font-size:30px}.page-heading p{margin:0;color:#64748b}.toolbar{display:flex;justify-content:space-between;align-items:center;margin:26px 0 14px;color:#94a3b8;font-size:12px}.toolbar mat-form-field{width:min(380px,100%)}.toolbar mat-icon{margin-right:8px;color:#94a3b8}.table{overflow:hidden;border:1px solid #e5e9f0;border-radius:14px;background:#fff}.table header,.table article{display:grid;grid-template-columns:2fr 1fr 1fr 130px;gap:16px;align-items:center;padding:14px 20px}.table header{color:#94a3b8;background:#f8fafc;font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.table article{border-top:1px solid #edf0f5}.identity{display:flex;gap:11px;align-items:center}.identity i{width:36px;height:36px;display:grid;place-items:center;border-radius:10px;color:#1d4ed8;background:#eff6ff;font-style:normal;font-size:10px;font-weight:800}.identity p{margin:0}.identity strong,.identity small{display:block}.identity strong{color:#334155;font-size:12px}.identity small,.muted{margin-top:3px;color:#94a3b8;font-size:10px}.roles{display:flex;gap:5px;flex-wrap:wrap}.roles b{padding:4px 7px;border-radius:7px;color:#1d4ed8;background:#eff6ff;font-size:9px}.role-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:28px}.role-grid article{padding:24px;border:1px solid #e5e9f0;border-radius:16px;background:#fff}.role-icon{width:46px;height:46px;display:grid;place-items:center;border-radius:13px;color:#2563eb;background:#eff6ff}.role-grid h2{margin:18px 0 7px;color:#334155}.role-grid p{min-height:42px;color:#64748b;line-height:1.6}.role-grid footer{display:flex;justify-content:space-between;align-items:center;margin-top:22px;padding-top:16px;border-top:1px solid #eef1f5;color:#64748b;font-size:11px}.badge{padding:4px 7px;border-radius:7px;background:#f1f5f9}.state{min-height:400px;display:grid;place-content:center;justify-items:center;text-align:center;color:#64748b}.state>mat-icon{width:46px;height:46px;font-size:46px;color:#94a3b8}.state h2{margin-bottom:0;color:#334155}.state p{max-width:460px;line-height:1.6}.denied>mat-icon{color:#2563eb}@media(max-width:800px){.table header{display:none}.table article{grid-template-columns:1fr auto}.table article>.roles,.table article>.muted{display:none}.role-grid{grid-template-columns:1fr}}
  `
})
export class AdminPage implements OnInit{
  private readonly api=inject(ApiService);private readonly route=inject(ActivatedRoute);private readonly fb=inject(FormBuilder);readonly mode=(this.route.snapshot.data['mode'] as 'users'|'roles')??'users';readonly users=signal<ManagedUserSummary[]>([]);readonly roles=signal<RoleSummary[]>([]);readonly loading=signal(true);readonly forbidden=signal(false);readonly error=signal('');readonly search=this.fb.nonNullable.control('');
  ngOnInit():void{this.load();this.search.valueChanges.pipe(debounceTime(250),distinctUntilChanged()).subscribe(()=>{if(this.mode==='users')this.load();});}load():void{this.loading.set(true);this.forbidden.set(false);this.error.set('');const request:Observable<PagedResult<ManagedUserSummary>|RoleSummary[]>=this.mode==='users'?this.api.users(this.search.value):this.api.roles();request.subscribe({next:(data:PagedResult<ManagedUserSummary>|RoleSummary[])=>{if(this.mode==='users')this.users.set((data as PagedResult<ManagedUserSummary>).items);else this.roles.set(data as RoleSummary[]);this.loading.set(false);},error:(response:HttpErrorResponse)=>{this.forbidden.set(response.status===403);this.error.set('Check the API connection and try again.');this.loading.set(false);}});}toggle(user:ManagedUserSummary,isActive:boolean):void{this.api.updateUserStatus(user.id,isActive).subscribe({next:updated=>this.users.update(items=>items.map(item=>item.id===updated.id?updated:item)),error:()=>this.load()});}initials(name:string):string{return name.split(' ').slice(0,2).map(part=>part[0]).join('').toUpperCase();}roleIcon(name:string):string{return name==='Admin'?'admin_panel_settings':name==='Manager'?'supervisor_account':'person';}
}
