<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>CloudTrack-Api-Local</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.11.4" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    <PackageReference Include="System.Formats.Asn1" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudTrack.Application\CloudTrack.Application.csproj" />
    <ProjectReference Include="..\CloudTrack.Infrastructure\CloudTrack.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup Condition="'$(IncludeFrontendDist)' == 'true'">
    <Content Include="$(MSBuildProjectDirectory)\..\..\..\frontend\dist\cloudtrack-web\browser\**\*" Link="wwwroot\%(RecursiveDir)%(Filename)%(Extension)" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <Target Name="EnsureWebRootExists" BeforeTargets="Build">
    <MakeDir Directories="$(MSBuildProjectDirectory)\wwwroot" />
  </Target>

</Project>
