import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { AuthService } from '../../core/auth.service';

@Component({selector:'app-profile-page',imports:[ReactiveFormsModule,MatButtonModule,MatFormFieldModule,MatIconModule,MatInputModule],template:`<div class="heading"><span>ACCOUNT</span><h1>Profile & security</h1><p>Review your identity and keep your account protected.</p></div><section class="profile-card"><div class="avatar">{{initials()}}</div><div><h2>{{auth.currentUser()?.displayName}}</h2><p>{{auth.currentUser()?.email}}</p><div class="roles">@for(role of auth.currentUser()?.roles;track role){<span>{{role}}</span>}</div></div></section><section class="security"><div><mat-icon>shield</mat-icon><h2>Change password</h2><p>Changing your password revokes every refresh token, including other devices.</p></div><form [formGroup]="form" (ngSubmit)="submit()"><mat-form-field appearance="outline"><mat-label>Current password</mat-label><input matInput type="password" formControlName="currentPassword" autocomplete="current-password" /></mat-form-field><mat-form-field appearance="outline"><mat-label>New password</mat-label><input matInput type="password" formControlName="newPassword" autocomplete="new-password" /></mat-form-field>@if(message()){<p class="message">{{message()}}</p>}<button mat-flat-button type="submit" [disabled]="form.invalid">Update password</button></form></section>`,styles:`.heading span{color:#2563eb;font-size:11px;font-weight:800;letter-spacing:.15em}.heading h1{margin:7px 0 6px;color:#0f172a;font-size:30px}.heading p{margin:0;color:#64748b}.profile-card,.security{margin-top:26px;padding:24px;border:1px solid #e5e9f0;border-radius:16px;background:#fff}.profile-card{display:flex;gap:18px;align-items:center}.avatar{width:64px;height:64px;display:grid;place-items:center;border-radius:18px;color:#fff;background:linear-gradient(135deg,#60a5fa,#1d4ed8);font-size:18px;font-weight:800}.profile-card h2{margin:0 0 4px;color:#334155}.profile-card p{margin:0;color:#64748b}.roles{display:flex;gap:6px;margin-top:10px}.roles span{padding:4px 8px;border-radius:8px;color:#1d4ed8;background:#eff6ff;font-size:10px;font-weight:750}.security{display:grid;grid-template-columns:1fr 1fr;gap:50px}.security>div>mat-icon{color:#2563eb}.security h2{margin:12px 0 5px;color:#334155}.security p{color:#64748b;line-height:1.6}.security form{display:grid}.message{padding:10px;border-radius:8px;background:#ecfdf5;color:#047857;font-size:12px}@media(max-width:700px){.security{grid-template-columns:1fr;gap:20px}}`})
export class ProfilePage{readonly auth=inject(AuthService);private readonly fb=inject(FormBuilder);readonly message=signal('');readonly form=this.fb.nonNullable.group({currentPassword:['',Validators.required],newPassword:['',[Validators.required,Validators.minLength(8)]]});submit():void{if(this.form.invalid)return;const value=this.form.getRawValue();this.auth.changePassword(value.currentPassword,value.newPassword).subscribe({next:()=>{this.message.set('Password updated. Sign in again to continue.');this.form.reset();},error:()=>this.message.set('Password could not be changed. Check the current password.')});}initials():string{return this.auth.currentUser()?.displayName.split(' ').slice(0,2).map(part=>part[0]).join('').toUpperCase()??'CT';}}

